// Authorization
export const AUTH_STARTED = 'AUTH_STARTED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';

// Loader
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

// UI Modal BlogPost
export const SHOW_MODAL_POST = 'SHOW_MODAL_POST';
export const HIDE_MODAL_POST = 'HIDE_MODAL_POST';

// Firebase database
export const FETCH_DATA_FROM_FIREBASE_SUCCESS = 'FETCH_DATA_FROM_FIREBASE_SUCCESS';
export const FETCH_DATA_FROM_FIREBASE_ERROR = 'FETCH_DATA_FROM_FIREBASE_ERROR';
export const FORCE_FETCH_DATA_FROM_FIREBASE_SUCCESS = 'FORCE_FETCH_DATA_FROM_FIREBASE_SUCCESS';
export const FORCE_FETCH_DATA_FROM_FIREBASE_ERROR = 'FORCE_FETCH_DATA_FROM_FIREBASE_ERROR';

// UI Modal Search
export const SHOW_MODAL_SEARCH = 'SHOW_MODAL_SEARCH';
export const HIDE_MODAL_SEARCH = 'HIDE_MODAL_SEARCH';

// Likes and dislikes
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const LIKE_POST_ERROR = 'LIKE_POST_ERROR';
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS';
export const DISLIKE_POST_ERROR = 'DISLIKE_POST_ERROR';

// UI Modal add comment
export const SHOW_MODAL_ADD_COMMENT = 'SHOW_MODAL_ADD_COMMENT';
export const HIDE_MODAL_ADD_COMMENT = 'HIDE_MODAL_ADD_COMMENT';

// Filter
export const APPLY_FILTER_TODAYS_POSTS = 'APPLY_FILTER_TODAYS_POSTS';
export const APPLY_FILTER_MOST_LIKED = 'APPLY_FILTER_MOST_LIKED';
export const APPLY_FILTER_HASHTAG = 'APPLY_FILTER_HASHTAG';
